import 'package:get/get.dart';

class Translation extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'title': 'Northern Border University',
          'publish_at': 'Published at : ',
          'who_we_are': 'Who We Are?',
          'contact_us': 'Contact US',
          'your_feedback': 'Your FeedBack',
          'give_your_feedback':
              'Give your valuable feedback to help us improve our app',
          'send': 'Send',
          'how_we_help': 'How can we help you?',
          'login_problem_help':
              'It looks like you are experiencing problems\nwith our sign up process. We are here to\nhelp so please get in touch with us',
          'chat_with_us': 'Chat with Us',
          'medicine': 'Faculty of Medicine',
          'arar': 'Arar',
          'std_info': 'Student Info',
          'email': 'Email',
          'phone': 'Phone',
          'apple_sign': 'Sign in with Apple',
          'website': 'Website',
          'about': 'About',
          'joined_date': 'Joined Date',
          'about_university': 'About the University',
          'view_more': 'view more',
          'university_history': 'University\'s History',
          'share_location': 'Share Location',
          'share_with': 'Share with',
          'settings': 'Settings',
          'change_password': 'Change Password',
          'change_language': 'Change Language',
          'change_location': 'Change Location',
          "getStart": "Get Started",
          "Skip": "Skip",
          'welcome_txt': "Welcome to NBU just one step to get started",
          'portal': 'University portal',
          'e-services': 'E-Services',
          'login': 'Login',
          'register': 'Register',
          'dont_have_account': 'Don\'t have an account? ',
          'welcome': 'Welcome',
          'join': 'Join Now and get started with NBU',
          'user_hint': 'Email',
          'password_hint': 'Password',
          'confirm_hint': 'Confirm Password',
          'forgot_password': 'Forgot Password',
          'or_login_with': 'or login with',
          'or': 'or',
          'profile': 'Profile',
          'my_services': 'My Services',
          'report': 'Report',
          'history': 'History',
          'search': 'Search',
          'Home': 'Home',
          'logout': 'Logout',
          'BlackBoard': 'BlackBoard',
          'Surveys': 'Surveys',
          'Admission and Registration (Students)':
              'Admission and Registration (Students)',
          'Academic calendar': 'Academic calendar',
          'Student Housing': 'Student Housing',
          'Scolarships': 'Scolarships',
          'E-Forms System': 'E-Forms System',
          'Employees Complaints': 'Employees Complaints',
          'Testahel': 'Testahel',
          'Office 365': 'Office 365',
          'E-mails': 'E-mails',
          'Digital Library': 'Digital Library',
          'Argos': 'Argos',
          'Symphony Library System': 'Symphony Library System',
          'Students Password Reset': 'Students Password Reset',
          'Marafiq - Operation and Maintenance':
              'Marafiq - Operation and Maintenance',
          'Blackboard Students': 'Blackboard Students',
          'Student Card Application': 'Student Card Application',
          'Admission and Registration (Faculty Members)':
              'Admission and Registration (Faculty Members)',
          'Research Management': 'Research Management',
          'Progress': 'Progress',
          'Employees Password Reset': 'Employees Password Reset',
          'Request a Computer': 'Request a Computer',
          'IP Phones': 'IP Phones',
          'E-transactions (Barq)': 'E-transactions (Barq)',
          'Self-Service Portal': 'Self-Service Portal',
          'SUPPORT-ME': 'SUPPORT-ME',
          'Majales': 'Majales',
          'Training Programs at Public Administration Institute':
              'Training Programs at Public Administration Institute',
          'Employee of the Year': 'Employee of the Year',
          'E-Archiving': 'E-Archiving',
          'Administration': 'Administration',
          'Media Center': 'Media Center',
          'Colleges': 'Colleges',
          'Magazine': 'Magazine',
          'About The University': 'About The University',
          'Gifted Students Academy': 'Gifted Students Academy',
          'Help': 'Help',
          'FeedBack': 'FeedBack',
          'Student Profile': 'Student Profile',
          'The President': 'The President',
          'The Resume': 'The Resume',
          'President Office': 'President Office',
          'Vice-President': 'Vice-President',
          'Deanship\'s': 'Deanship\'s',
          'Centers': 'Centers',
          'Administrations': 'Administrations',
          'Faculty Members': 'Faculty Members',
          'Received App Updates': 'Received App Updates',
          'Received Notification': 'Received Notification',
          "Notification Settings": "Notification Settings",
          "SAVE": 'SAVE',
          "CANCEL": "CANCEL",
          'Profile photo updated successfully.':
              'Profile photo updated successfully.',
          "Edit Profile": "Edit Profile",
          'News': 'News',
          'News in videos, photos and other':
              'News in videos, photos and other',
          'Events': 'Events',
          'Events maybe you interested in': 'Events maybe you interested in',
          'Announcements': 'Announcements',
          'Announcements about things you cares about':
              'Announcements about things you cares about',
          'Photos': 'Photos',
          'Gallery of NBU events': 'Gallery of NBU events',
          'Videos': 'Videos',
          'Videos for everything happens in NBU':
              'Videos for everything happens in NBU',
        },
        'ar_SA': {
          'title': 'Northern Border University',
          'publish_at': 'تاريخ النشر : ',
          'who_we_are': 'من نحن ؟',
          'contact_us': 'تواصل معنا',
          'your_feedback': 'تقييمك',
          'Student Profile': 'الحساب الشخصي',
          'give_your_feedback': 'قم بتقييم التطبيق لمساعدتنا في التطوير',
          'send': 'أرسل',
          'how_we_help': 'كيف يمكننا مساعدتك ؟',
          'login_problem_help':
              'يبدو أنك تواجه مشاكل في التسجيل نحن هنا لمساعدتك كن على اتصال معنا',
          'chat_with_us': 'تواصل معنا',
          'medicine': 'كلية الطب',
          'arar': 'عرعر',
          'std_info': 'بيانات الطالب',
          'email': 'البريد الإلكتروني',
          'phone': 'الهاتف',
          'website': 'الموقع الإلكتروني',
          'about': 'عن الطالب',
          'joined_date': 'تاريخ الإنضمام',
          'about_university': 'عن الجامعة',
          'view_more': 'عرض المزيد',
          'university_history': 'تاريخ الجامعة',
          'share_location': 'مشاركة الموقع',
          'share_with': 'مشاركة باستخدام',
          'settings': 'الإعدادات',
          'change_password': 'تغير كلمة المرور',
          'change_language': 'تغيير اللغة',
          'change_location': 'تغيير الموقع',
          "getStart": "البدء",
          "Skip": "تخطى",
          'welcome_txt': "مرحبا بك في جامعة الحدود الشمالية خطوة واحدة للبدء",
          'portal': "الـبـوابـة الجـامـعيـة",
          'e-services': "الخدمات الإلكترونية",
          'login': 'تسجيل الدخول',
          'apple_sign': 'تسجيل الدخول بواسطة أبل',
          'register': 'إنشاء حساب جديد',
          'dont_have_account': 'ليس لدي حساب ؟ ',
          'welcome': 'مرحبا',
          'join': 'قم بالإنضمام الآن والبدء مع جامعة الحدود الشمالية',
          'user_hint': 'البريد الإلكتروني',
          'password_hint': 'كلمة المرور',
          'confirm_hint': 'تأكيد كلمة المرور',
          'forgot_password': 'نسيت كلمة المرور',
          'or_login_with': 'أو التسجيل بـ',
          'or': 'أو',
          'profile': 'الحساب الشخصي',
          'my_services': 'خدماتي',
          'report': 'إبلاغ',
          'history': 'التاريخ',
          'search': 'بحث',
          'Home': 'الصفحة الرئيسية',
          'logout': 'تسجيل الخروج',
          'BlackBoard': 'بلاك بورد',
          'Surveys': 'الإستبيانات',
          'Admission and Registration (Students)':
              'نظام القبول والتسجيل -بانر (الطلبة)',
          'Academic calendar': 'التقويم الاكاديمي',
          'Student Housing': 'إسكان الطلبة',
          'Scolarships': 'المنح الدراسية',
          'E-Forms System': 'نظام النماذج الإلكترونية',
          'Employees Complaints': 'منصة تظلمات الموظفين',
          'Testahel': 'تستاهل',
          'Office 365': 'Office 365',
          'E-mails': 'البريد الإلكتروني',
          'Digital Library': 'المكتبة الرقمية',
          'Argos': ' ارغوس',
          'Symphony Library System': 'نظام المكتبات (Symphony)',
          'Students Password Reset': 'اعادة كلمة المرور لطلبة الجامعة',
          'Marafiq - Operation and Maintenance':
              'نظام الصيانة والتشغيل - مرافق',
          'Blackboard Students': 'نظام التعليم الإلكتروني (بلاك بورد)',
          'Student Card Application': 'اصدار بطاقة',
          'Admission and Registration (Faculty Members)':
              'نظام القبول والتسجيل -بانر (أعضاء هيئة التدريس)',
          'Research Management': 'ادارة الابحاث',
          'Progress': 'توثيق المهام اليومية',
          'Employees Password Reset': 'إعادة تعيين كلمة المرور للموظفين',
          'Request a Computer': 'طلب جهاز حاسب آلي',
          'IP Phones': 'خدمة الهاتف الشبكي',
          'E-transactions (Barq)': 'التعاملات الالكترونية (برق)',
          'Self-Service Portal': 'بوابة الخدمة الذاتية',
          'SUPPORT-ME': 'إدعمني',
          'Majales': 'مجالس',
          'Training Programs at Public Administration Institute':
              'دورات معهد الإدارة',
          'Employee of the Year': 'جائزة الموظف المثالي',
          'E-Archiving': 'نظام الأرشفة الرقمية',
          'Administration': 'إدارة الجامعة',
          'Media Center': 'المركز الإعلامى',
          'Colleges': 'الكليات',
          'Magazine': 'مجلة الشمال العلمية',
          'About The University': 'عن الجامعة',
          'Gifted Students Academy': 'أكاديمية الموهوبين',
          'Help': 'المساعدة',
          'FeedBack': 'التقييم',
          'The President': 'كلمة رئيس الجامعة',
          'The Resume': 'السيرة الذاتية لمعالي رئيس الجامعة',
          'President Office': 'مكتب رئيس الجامعة',
          'Vice-President': 'الوكالات',
          'Deanship\'s': 'العمادات',
          'Centers': 'المراكز',
          'Administrations': 'الإدارات',
          'Faculty Members': 'أعضاء الهيئة التدريسية',
          'Received App Updates': 'إستلام تحديثات التطبيق',
          'Received Notification': 'إستقبال الإشعارات',
          "Notification Settings": "إعدادات الإشعارات",
          "SAVE": 'حفظ',
          "CANCEL": "إغلاق",
          'Profile photo updated successfully.':
              'تم تعديل صورة الملف الشخصي بنجاح',
          "Edit Profile": "تعديل الملف الشخصي",
          'News': 'الأخبار',
          'News in videos, photos and other': 'صور , فيديو أخر الأخبار',
          'Events': 'الفعاليات',
          'Events maybe you interested in': 'عرض جميع الفعاليات',
          'Announcements': 'الإعلانات',
          'Announcements about things you cares about': 'عرض جميع الإعلانات',
          'Photos': 'معرض الصور',
          'Gallery of NBU events': 'عرض معرض الصور',
          'Videos': 'معرض الفيديو',
          'Videos for everything happens in NBU': 'عرض معرض الفيديو',
        }
      };
}
